### ISSUE TITLE
Publish documentation on gh-pages using circleci

### ISSUE THREAD

**Issue by axic** [ewasm/ewasm-rust-api#20]

**Comment by jakelang** [comment]
@axic I need write access to this repo to set up gh-pages.

**Comment by axic** [comment]
@jakelang you have write access

**Comment by axic** [comment]
It is published as a crate here: https://docs.rs/ewasm_api/0.4.0/ewasm_api/

**Comment by axic** [comment]
And here: https://docs.rs/crate/ewasm_api
