### ISSUE TITLE
Implement "primitive allocator" which never frees

### ISSUE THREAD

**Issue by axic** [ewasm/ewasm-rust-api#46]
This is (probably) useful for precompiles.

**Comment by axic** [comment]
Maybe there's no need to write this as this could be sufficient: https://github.com/fitzgen/bumpalo

**Comment by s1na** [comment]
Bumpalo depends itself on an existing global allocator and I'm not sure if it can be used as a replacement for the `std` alloc.

**Comment by axic** [comment]
You're correct @s1na this seems to be a layer on top of `alloc`. Practically we want to achieve the same what it does, but purely on the low-level.
