### ISSUE TITLE
Cleaning up "features"

### ISSUE THREAD

**Issue by axic** [ewasm/ewasm-rust-api#58]
Right now we have:
- std/no_std
- wee_alloc/qimalloc/stdalloc
- one feature for each optional EEI: debug, experimental, bignum, eth2 (these would be merged into master once stable)

This is spawning this build hell as seen in #56.

Perhaps bignum could go under experimental. With time as these features mature, they wouldn't need to be conditionally enabled.

Maybe debug doesn't even need to be a feature, just made available. Idea by @jakelang to only enable the debug module when compiling in debug mode. Extending on that: how about making them macros which are compiled to nop in release mode?

**Comment by jakelang** [comment]
We don't necessarily need to make them macros, but this is a nice idea because we can completely remove the code at compile-time rather than have calls to stub functions.

**Comment by axic** [comment]
We've already remove the "bignum" feature and created #63 to track the "debug" feature.

It seems we'll end up with:
- std/not_std
- (option to use other allocators)
- "experimental" and "eth2" features

I think this is more manageable now.
