### ISSUE TITLE
consider adding a `main` function to `src\main.rs`

### ISSUE THREAD

**Issue by oracle3** [ewasm/ewasm-rust-api#74]
use ewasm_api::prelude::*;

fn entry() {
    let a: Hash = block_hash(1);
    finish_data(&a.bytes);
}

ewasm_entry_point!(entry);

error[E0601]: `main` function not found in crate `myrust`
  |
  = note: consider adding a `main` function to `src\main.rs`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0601`.

**Comment by axic** [comment]
You create should be compiled as `cdylib` and not as an app. That's why `main` is not needed. We should document this though.

**Comment by axic** [comment]
@oracle3 documented this in #75.
